//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int nhanvien_id { get; set; }
        public string ten { get; set; }
        public Nullable<int> tuoi { get; set; }
        public string chucvu { get; set; }
        public Nullable<System.DateTime> ngayvaolam { get; set; }
        public Nullable<double> luong { get; set; }
    }
}
