//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Details
    {
        public int Orders_id { get; set; }
        public int Products_id { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Gia { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
