//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders_Details = new HashSet<Orders_Details>();
        }
    
        public int Products_id { get; set; }
        public string Name { get; set; }
        public string HangCPU { get; set; }
        public string CNCPU { get; set; }
        public string TocDoMax { get; set; }
        public string MemoryRam { get; set; }
        public string LoaiRam { get; set; }
        public string BusRam { get; set; }
        public Nullable<int> KheRam { get; set; }
        public string ODia { get; set; }
        public string DungLuongODia { get; set; }
        public string CardDohoa { get; set; }
        public string ManhHinh { get; set; }
        public string Dophangiai { get; set; }
        public string Motasp { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> Discount_id { get; set; }
        public Nullable<int> Hangsx_id { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Hangsx Hangsx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Details> Orders_Details { get; set; }
    }
}
